// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OperacaoPato.Backend.Infrastructure.Data;

#nullable disable

namespace OperacaoPato.Backend.Infrastructure.Migrations
{
    [DbContext(typeof(OperacaoPatoContext))]
    partial class OperacaoPatoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OperacaoPato.Backend.Domain.Entities.PatoPrimordial", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("BatimentosPorMinuto")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataColetaUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("DroneNumeroSerie")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("QuantidadeMutacoes")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Patos");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            DataColetaUtc = new DateTime(2025, 10, 23, 9, 0, 0, 0, DateTimeKind.Local),
                            DroneNumeroSerie = "DRONE-001",
                            QuantidadeMutacoes = 2,
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            BatimentosPorMinuto = 30,
                            DataColetaUtc = new DateTime(2025, 10, 24, 9, 0, 0, 0, DateTimeKind.Local),
                            DroneNumeroSerie = "DRONE-002",
                            QuantidadeMutacoes = 3,
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            BatimentosPorMinuto = 15,
                            DataColetaUtc = new DateTime(2025, 10, 25, 9, 0, 0, 0, DateTimeKind.Local),
                            DroneNumeroSerie = "DRONE-003",
                            QuantidadeMutacoes = 5,
                            Status = 2
                        });
                });

            modelBuilder.Entity("OperacaoPato.Domain.Entities.Drone", b =>
                {
                    b.Property<string>("NumeroSerie")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Fabricante")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PaisOrigem")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("NumeroSerie");

                    b.ToTable("Drones");

                    b.HasData(
                        new
                        {
                            NumeroSerie = "DRONE-001",
                            Fabricante = "DJI Technology",
                            Marca = "DJI",
                            PaisOrigem = "China"
                        },
                        new
                        {
                            NumeroSerie = "DRONE-002",
                            Fabricante = "Parrot SA",
                            Marca = "Parrot",
                            PaisOrigem = "França"
                        },
                        new
                        {
                            NumeroSerie = "DRONE-003",
                            Fabricante = "Skydio Inc",
                            Marca = "Skydio",
                            PaisOrigem = "Estados Unidos"
                        },
                        new
                        {
                            NumeroSerie = "DRONE-004",
                            Fabricante = "Autel Robotics",
                            Marca = "Autel",
                            PaisOrigem = "China"
                        },
                        new
                        {
                            NumeroSerie = "DRONE-005",
                            Fabricante = "PowerVision Tech",
                            Marca = "PowerVision",
                            PaisOrigem = "China"
                        });
                });

            modelBuilder.Entity("OperacaoPato.Backend.Domain.Entities.PatoPrimordial", b =>
                {
                    b.OwnsOne("OperacaoPato.Domain.ValueObjects.Comprimento", "Altura", b1 =>
                        {
                            b1.Property<Guid>("PatoPrimordialId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("UnidadeComprimento")
                                .HasColumnType("int")
                                .HasColumnName("Altura_Unidade");

                            b1.Property<double>("Valor")
                                .HasColumnType("float")
                                .HasColumnName("Altura_Valor");

                            b1.HasKey("PatoPrimordialId");

                            b1.ToTable("Patos");

                            b1.WithOwner()
                                .HasForeignKey("PatoPrimordialId");
                        });

                    b.OwnsOne("OperacaoPato.Backend.Domain.Entities.SuperPoder", "Poder", b1 =>
                        {
                            b1.Property<Guid>("PatoPrimordialId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Classificacao")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("Poder_Classificacao");

                            b1.Property<string>("Descricao")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)")
                                .HasColumnName("Poder_Descricao");

                            b1.Property<string>("Nome")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Poder_Nome");

                            b1.HasKey("PatoPrimordialId");

                            b1.ToTable("Patos");

                            b1.WithOwner()
                                .HasForeignKey("PatoPrimordialId");
                        });

                    b.OwnsOne("OperacaoPato.Backend.Domain.ValueObjects.Localizacao", "Localizacao", b1 =>
                        {
                            b1.Property<Guid>("PatoPrimordialId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Cidade")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Localizacao_Cidade");

                            b1.Property<string>("Pais")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Localizacao_Pais");

                            b1.Property<string>("PontoReferencia")
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("Localizacao_PontoReferencia");

                            b1.HasKey("PatoPrimordialId");

                            b1.ToTable("Patos");

                            b1.WithOwner()
                                .HasForeignKey("PatoPrimordialId");

                            b1.OwnsOne("OperacaoPato.Backend.Domain.ValueObjects.Coordenada", "Coordenada", b2 =>
                                {
                                    b2.Property<Guid>("LocalizacaoPatoPrimordialId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<double>("Latitude")
                                        .HasColumnType("float")
                                        .HasColumnName("Localizacao_Latitude");

                                    b2.Property<double>("Longitude")
                                        .HasColumnType("float")
                                        .HasColumnName("Localizacao_Longitude");

                                    b2.HasKey("LocalizacaoPatoPrimordialId");

                                    b2.ToTable("Patos");

                                    b2.WithOwner()
                                        .HasForeignKey("LocalizacaoPatoPrimordialId");
                                });

                            b1.OwnsOne("OperacaoPato.Domain.ValueObjects.Comprimento", "Precisao", b2 =>
                                {
                                    b2.Property<Guid>("LocalizacaoPatoPrimordialId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<int>("UnidadeComprimento")
                                        .HasColumnType("int")
                                        .HasColumnName("Localizacao_Precisao_Unidade");

                                    b2.Property<double>("Valor")
                                        .HasColumnType("float")
                                        .HasColumnName("Localizacao_Precisao_Valor");

                                    b2.HasKey("LocalizacaoPatoPrimordialId");

                                    b2.ToTable("Patos");

                                    b2.WithOwner()
                                        .HasForeignKey("LocalizacaoPatoPrimordialId");
                                });

                            b1.Navigation("Coordenada")
                                .IsRequired();

                            b1.Navigation("Precisao")
                                .IsRequired();
                        });

                    b.OwnsOne("OperacaoPato.Backend.Domain.ValueObjects.Massa", "Peso", b1 =>
                        {
                            b1.Property<Guid>("PatoPrimordialId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("UnidadeMassa")
                                .HasColumnType("int")
                                .HasColumnName("Peso_Unidade");

                            b1.Property<double>("Valor")
                                .HasColumnType("float")
                                .HasColumnName("Peso_Valor");

                            b1.HasKey("PatoPrimordialId");

                            b1.ToTable("Patos");

                            b1.WithOwner()
                                .HasForeignKey("PatoPrimordialId");
                        });

                    b.Navigation("Altura")
                        .IsRequired();

                    b.Navigation("Localizacao")
                        .IsRequired();

                    b.Navigation("Peso")
                        .IsRequired();

                    b.Navigation("Poder")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
